spring.application.name=fedex

# disable Docker integration
spring.docker.compose.enabled=false

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5434/test_db
spring.datasource.username=postgres
spring.datasource.password=postgres


# JPA / Hibernate settings
# spring.jpa.hibernate.ddl-auto=create -> refresh the database every run and all values are removed
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# resolve the n+1 query problem
#spring.jpa.open-in-view=false

# JWT
jwt.secret=ZmWEdGV4LWFwcC1qd3Qtc2VjcmV0LWtleS1hdC1sZWFzdC0yNTYtYml0cy1sb25nLWFuZC12ZXJ5LXNlY3VyZSEh
jwt.expiration=86400000
# 24 hours in milliseconds for expiration

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.schema.printer.enabled=true
spring.graphql.schema.location=classpath:graphql/

# Redis Cache
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

# Enable cache logging
logging.level.org.springframework.cache=TRACE
logging.level.com.example.fedex.service.UserDetailsServiceImpl=DEBUG

# Handle Java 8 date/time type serialization
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.adjust-dates-to-context-time-zone=false
spring.jackson.time-zone=UTC

# Use the local storage for File storage configuration
label.storage.directory=generated-labels
label.storage.auto-create=true
label.storage.max-files=1000

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=fedex-shipment-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Create kafka topics automatically
#spring.kafka.admin.properties.auto.create.topics.enable=true

# Twilio Configuration
twilio.accountSid=AC98f820dec5fefd2140bfba38a4b584d4
twilio.authToken=9337f48aa50bd5585ab7079fa0e3be94
twilio.phoneNumber=+18444460782

# Server
server.port=8081