spring.application.name=fedex

# disable Docker integration
spring.docker.compose.enabled=false

# Database connection for local setup
spring.datasource.url=jdbc:postgresql://localhost:5434/test_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Azure Database for PostgreSQL
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA / Hibernate settings
# spring.jpa.hibernate.ddl-auto=create -> refresh the database every run and all values are removed
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# resolve the n+1 query problem
#spring.jpa.open-in-view=false

# JWT
jwt.secret=ZmWEdGV4LWFwcC1qd3Qtc2VjcmV0LWtleS1hdC1sZWFzdC0yNTYtYml0cy1sb25nLWFuZC12ZXJ5LXNlY3VyZSEh
jwt.expiration=86400000
# 24 hours in milliseconds for expiration

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.schema.printer.enabled=true
spring.graphql.schema.location=classpath:graphql/

# Redis Cache in Local
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.cache.type=redis

# Azure Cache for Redis using environment variable.
#spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
#spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
#spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}

# Azure Cache for Redis using direct values
spring.data.redis.host=fedex.redis.cache.windows.net
spring.data.redis.port=6380
spring.data.redis.password=3OAQg5Mk0HZlK6v4Dwcd01ge9p1HYkmPRAzCaA0NVR0=
spring.data.redis.ssl.enabled=true
spring.cache.type=redis

# Enable cache logging
logging.level.org.springframework.cache=TRACE
logging.level.com.example.fedex.service.UserDetailsServiceImpl=DEBUG

# Handle Java 8 date/time type serialization
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.adjust-dates-to-context-time-zone=false
spring.jackson.time-zone=UTC

# Server
#server.port=8080
server.port=${PORT:8080}

# To use ngrok public url
external.api.base-url=https://eb77b0d40085.ngrok-free.app