spring.application.name=fedex

# disable Docker integration
spring.docker.compose.enabled=false

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5434/test_db
spring.datasource.username=postgres
spring.datasource.password=postgres


# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# resolve the n+1 query problem
#spring.jpa.open-in-view = false

# JWT
jwt.secret=a-string-secret-at-least-256-bits-long
jwt.expiration=86400000
# 24 hours in milliseconds for expiration

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.schema.printer.enabled=true
spring.graphql.schema.location=classpath:graphql/

# Server
server.port=8080