enum Role {
    USER
    ADMIN
}

type User {
    id: ID!
    username: String!
    email: String!
    roles: [Role!]!
}

type AuthPayload {
    token: String!
    user: User!
}

type Query {
    currentUser: User!
    users: [User!]!
    roles: [Role!]!
    allShippingDetails: [ShippingDetails!]!
    shippingDetailsById(id: ID!): ShippingDetails
    shippingDetailsByTrackingNumber(trackingNumber: String!): ShippingDetails
    searchShippingByFirstName(firstName: String!): [ShippingDetails!]!
    shippingByDeliveryMode(deliveryMode: DeliveryMode!): [ShippingDetails!]!
}

type Mutation {
    signIn(input: SignInInput!): AuthPayload!
    signUp(input: SignUpInput!): SignUpResponse!
    updateUserRoles(id: ID!, roles: [Role!]!): User!
    deleteUser(id: ID!): Boolean!
    createShippingDetails(input: ShippingInput!): ShippingDetails!
    updateShippingDetails(id: ID!, input: ShippingInput!): ShippingDetails!
    deleteShippingDetails(id: ID!): Boolean!
}

input SignInInput {
    username: String!
    password: String!
}

input SignUpInput {
    username: String!
    email: String!
    password: String!
    roles: [Role!]
}

type SignUpResponse {
    message: String
    success: Boolean!
    error: String
}

type ShippingDetails {
    id: ID!
    firstName: String!
    lastName: String!
    fromName: String!
    contactNumber: String!
    shippingAddress: String!
    deliveryMode: DeliveryMode!
    price: Float!
    trackingNumber: String!
    createdAt: String!
    updatedAt: String!
}

input ShippingInput {
    firstName: String!
    lastName: String!
    fromName: String!
    contactNumber: String!
    shippingAddress: String!
    deliveryMode: DeliveryMode!
    price: Float!
}

enum DeliveryMode {
    STANDARD
    EXPRESS
    PRIORITY
    SAME_DAY
    INTERNATIONAL
}
