enum Role {
    USER
    ADMIN
}

type User {
    id: ID!
    username: String!
    email: String!
    roles: [Role!]!
}

type AuthPayload {
    token: String!
    user: User!
}

type Query {
    currentUser: User!
    users: [User!]!
    roles: [Role!]!
    allShippingDetails: [ShippingDetails!]!
    shippingDetailsById(id: ID!): ShippingDetails
    shippingDetailsByTrackingNumber(trackingNumber: String!): ShippingDetails
    searchShippingByFirstName(firstName: String!): [ShippingDetails!]!
    shippingByDeliveryMode(deliveryMode: DeliveryMode!): [ShippingDetails!]!

    # Shipment Details Given Formate
    getShipmentById(id: ID!): ShipmentDetailResponse
    getAllShipments: [ShipmentDetailResponse]!

    # PricePlan Details
    allPricePlanDetails: [PricePlanResponse]!
    getPricePlanDetailById(id: ID!): PricePlanResponse

    #  Label Generation
    generateShippingLabel(shipmentId: Int!): LabelResponse!
    getShippingLabel(shipmentId: Int!): LabelResponse!

}

type Mutation {
    signIn(input: SignInInput!): AuthPayload!
    signUp(input: SignUpInput!): SignUpResponse!
    updateUserRoles(id: ID!, roles: [Role!]!): User!
    deleteUser(id: ID!): Boolean!
    createShippingDetails(input: ShippingInput!): ShippingDetails!
    updateShippingDetails(id: ID!, input: ShippingInput!): ShippingDetails!
    deleteShippingDetails(id: ID!): Boolean!

#    Shipment Details Given Formate
    createShipmentDetail(input: ShipmentInput!): ShipmentDetailResponse!
    updateShipmentDetail(id: Int, input: ShipmentInput): ShipmentDetailResponse!
    deleteShipmentDetail(id: Int): Boolean!

    createPlanPriceDetails(input: PricePlanInput!): PricePlanResponse!
    updatePricePlanDetails(id: ID!, input: PricePlanInput!): PricePlanResponse!
    deletePricePlanDetails(id: Int!): Boolean!

#    Event Streaming
    createTestMessage(message: String!): String!
    updateShipmentStatus(shipmentId: Int, input: ShipmentStatusInput): ShipmentDetailResponse!
}

type LabelResponse {
    labelId: ID
    pdfContent: String
    fileName: String
    fileType: String
    fileSize: Int
    createdDate: String
    updatedDate: String
}

input ShipmentStatusInput {
    shippingStatus: ShippingStatus!
}


input PricePlanInput {
    pricingPlanId: Int!,
    detailId: Int!,
    fromWeight: String!,
    toWeight: String!,
    price: Float!
}

type PricePlanResponse {
    planId: Int!,
    pricingPlanId: Int!,
    detailId: Int!,
    fromWeight: String!,
    toWeight: String!,
    price: Float!
}

input PlanCountry {
    pricingPlanId: Int!
    countryCode:String!
}

type PricePlanCountry {
    Plan_id:Int!
    PricingPlanId:Int!
    CountryCode:String!
}

input SignInInput {
    username: String!
    password: String!
}

input SignUpInput {
    username: String!
    email: String!
    password: String!
    roles: [Role!]
}

type SignUpResponse {
    message: String
    success: Boolean!
    error: String
}


input UserInput {
    firstName: String!
    middleName: String
    lastName: String!
    sex: String!
}

input FromAddressInput {
    userId: Int
    apt: String
    name: String!
    city: String!
    state: String!
    zipcode: String!
}

input ToAddressInput {
    userId: Int
    apt: String
    name: String!
    city: String!
    state: String!
    zipcode: String!
}

input TrackingInput {
    trackingNumber: String
    status: String
}

input ContactInfoInput {
    userId: Int
    phoneNumber: String!
    email: String!
}

input ShipmentInput {
    userDetails: UserInput!
    weight: String!
    qty: String!
    fromAddress: FromAddressInput!
    toAddress: ToAddressInput!
    modeOfDelivery: DeliveryMode!
    shippingStatus: ShippingStatus
    price: Float
    contactInfo: ContactInfoInput!
}

type UserDetailsType {
    firstName: String!
    middleName: String
    lastName: String!
    sex: String!
}

type FromAddressType {
    userId: Int!
    apt: String
    name: String!
    city: String!
    state: String!
    zipcode: String!
}

type ToAddressType {
    userId: Int!
    apt: String
    name: String!
    city: String!
    state: String!
    zipcode: String!
}

type TrackingType {
    labelId: String
    trackingNumber: String
    createdDate: String
    updatedDate: String
}

type LabelCreationType {
    labelId: String
    pdfContent: String
    fileName: String
    fileType: String
    fileSize: Int
    createdDate: String
    updatedDate: String
}

type ContactInfoType {
    userId: Int!
    phoneNumber: String!
    email: String!
}

type ShipmentDetailResponse {
    shipmentId: ID!
    userDetails: UserDetailsType!
    weight: String!
    qty: String!
    fromAddress: FromAddressType!
    toAddress: ToAddressType!
    modeOfDelivery: DeliveryMode!
    shippingStatus: ShippingStatus!
    price: Float!
    tracking: TrackingType
    labelCreation: LabelCreationType
    contactInfo: ContactInfoType!
}



type ShippingDetails {
    id: ID!
    senderFirstName: String!
    senderLastName: String!
    senderEmail: String!
    senderContactNumber: String!
    senderAddress: String!
    receiverFirstName: String!
    receiverLastName: String!
    receiverEmail: String!
    receiverContactNumber: String!
    receiverAddress: String!
    deliveryMode: DeliveryMode!
    price: Float!
    shippingStatus: ShippingStatus!
    trackingNumber: String!
    createdAt: String!
    updatedAt: String!
}

input ShippingInput {
    senderFirstName: String!
    senderLastName: String!
    senderEmail: String!
    senderContactNumber: String!
    senderAddress: String!
    receiverFirstName: String!
    receiverLastName: String!
    receiverEmail: String!
    receiverContactNumber: String!
    receiverAddress: String!
    deliveryMode: DeliveryMode!
    price: Float!
    shippingStatus: ShippingStatus!
}

enum DeliveryMode {
    EXPRESS,
    STANDARD,
    ECONOMY,
    INTERNATIONAL,
    SAME_DAY,
    OVERNIGHT,
    FREIGHT,
    GROUND
}

enum ShippingStatus {
    PENDING,
    PICKED_UP,
    IN_TRANSIT,
    OUT_FOR_DELIVERY,
    DELIVERED,
    FAILED_DELIVERY,
    RETURNED,
    CANCELLED,
    ON_HOLD,
    CUSTOMS_CLEARANCE,
    EXCEPTION
}
